name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Enviar arquivos para VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # password: ${{ secrets.VPS_PASSWD }}
          port: 22
          source: "."
          target: "~/minha-aplicacao/public"
          rm: false
          strip_components: 0
          exclude: "node_modules"

      - name: Executar comandos na VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # password: ${{ secrets.VPS_PASSWD }}
          port: 22
          script: |
            cd ~/minha-aplicacao/public
            
            # Parar o processo anterior (se estiver rodando na porta 3000, por exemplo)
            PID=$(lsof -t -i:3000) && if [ -n "$PID" ]; then kill -9 $PID; fi

            # Instalar dependências para produção
            npm install --production

            # Executar em segundo plano
            nohup npm run prod > output.log 2>&1 &