name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Enviar arquivos para VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: 1903Portfolio$$
          port: 22
          source: "."
          target: "/home/portfolio"
          rm: false
          strip_components: 0
          exclude: "node_modules"

      - name: Executar comandos na VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: 1903Portfolio$$
          port: 22
          script: |
            cd /home/portfolio
            npm install --production
            npm run prod